version: '3.7'
services:
  php:
    volumes:
      - .:/var/www/html/
    networks:
      - web-public
    image: serversideup/php:beta-8.0-fpm-apache
    ports:
      - 80:80
      - 443:443
    environment:
      APACHE_DOCUMENT_ROOT: "/var/www/html/public"
  
  mariadb:
    image: mariadb:10.5
    hostname: "wordpress_mariadb"
    networks:
      - web-public
    environment:
        MYSQL_ROOT_PASSWORD: "rootpassword"
        MARIADB_DATABASE: "wordpress"
        MARIADB_USER: "wordpress_database_user"
        MARIADB_PASSWORD: "wordpress_database_password"
    volumes:
      # Add volume for all database files
      - ./_volumes/mysql/database_data/:/var/lib/mysql
      # Add volume for custom configurations
      - ./_volumes/mysql/conf.d/:/etc/mysql/conf.d
      - ./_volumes/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - target: 3306
        published: 3306
        mode: host

networks:
  web-public:
